var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var e=a.length,d=0;d<e;d++){var f=a[d];if(b.call(c,f,d,a))return{i:d,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,e){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,e):$jscomp.polyfillUnisolated(a,b,c,e))};$jscomp.polyfillUnisolated=function(a,b,c,e){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];d in c||(c[d]={});c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,e){var d=a.split(".");a=1===d.length;e=d[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<d.length-1;f++){var g=d[f];g in e||(e[g]={});e=e[g]}d=d[d.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?e[d]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+d,d=$jscomp.propertyToPolyfillSymbol[d],
$jscomp.defineProperty(e,d,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");$("#conout").on("hidden.bs.collapse",function(){$("#conout-folder span").text("\uf077");forceResize()}).on("shown.bs.collapse",function(){$("#conout-folder span").text("\uf078");forceResize()});
$("#sidebar").on("hidden.bs.collapse",function(){$("#sidebar-folder span").text("\uf053");forceResize()}).on("shown.bs.collapse",function(){$("#sidebar-folder span").text("\uf054");forceResize()});
for(var overrideBlock=function(a,b){var c=Blockly.Blocks[a].init;Blockly.Blocks[a].init=function(){c.call(this);b(this)}},overrideColour=function(a,b){overrideBlock(a,function(a){a.setColour(b)})},square_blocks="text text_join text_charAt text_getSubstring text_changeCase text_trim text_replace text_reverse".split(" "),i=0;i<square_blocks.length;i++)overrideBlock(square_blocks[i],function(a){a.setOutputShape(Blockly.OUTPUT_SHAPE_SQUARE)});
Blockly.Themes.Classic.categoryStyles={event_category:{colour:"#ffbf00"},env_category:{colour:"#b26b47"},hid_category:{colour:"#4759b2"},control_category:{colour:"#477cb2"},math_category:{colour:"#59c059"},text_category:{colour:"#9966ff"},list_category:{colour:260},colour_category:{colour:"#000000"},variable_category:{colour:"#ff8c1a"},procedure_category:{colour:"290"},advanced_category:{colour:"0"}};Blockly.Msg.VARIABLES_HUE="#ff8c1a";Blockly.Themes.Classic.blockStyles.variable_blocks={colourPrimary:"#ff8c1a"};
overrideColour("ahk_evt_auto_execute","#ffbf00");Blockly.HSV_SATURATION=.6;Blockly.HSV_VALUE=.7;var workspace=null,allDeclarationElementsSelector="#function-editor-controls button, #function-editor-xml-controls button, #function-editor-xml",isEditingDeclaration=!1,callback=null,mutationRoot=null,declarationWorkspace=null;function forceResize(){var a=window.document.createEvent("UIEvents");a.initUIEvent("resize",!0,!1,window,0);window.dispatchEvent(a)}
function myUpdateFunction(){if(!workspace.isDragging()){var a=document.querySelector("#code");a.innerText=Blockly.AutoHotkey.workspaceToCode(workspace);a.classList.remove("prettyprinted");PR.prettyPrint()}}function clearWorkspaceAndLoadFromXml(a,b){b.setResizesEnabled(!1);b.clear();Blockly.Xml.domToWorkspace(a,b);b.setResizesEnabled(!0)}
function closeDeclarationWorkspace(){mutationRoot=callback=null;declarationWorkspace.clear();workspace.refreshToolboxSelection();disableDeclarationControls();$("#page-1").removeClass("d-none").addClass("d-flex");$("#page-2").removeClass("d-flex").addClass("d-none");forceResize()}function applyMutation(){var a=mutationRoot.mutationToDom();Blockly.Functions.validateFunctionExternal(a,workspace)&&(callback(a),closeDeclarationWorkspace())}function addBoolean(){mutationRoot.addBooleanExternal()}
function addNumber(){mutationRoot.addNumberExternal()}function addText(){mutationRoot.addStringExternal()}function addCustom(){mutationRoot.addCustomExternal("CustomType")}function enableDeclarationControls(){for(var a=document.querySelectorAll(allDeclarationElementsSelector),b=0;b<a.length;++b)a[b].removeAttribute("disabled");isEditingDeclaration=!0}
function disableDeclarationControls(){for(var a=document.querySelectorAll(allDeclarationElementsSelector),b=0;b<a.length;++b)a[b].setAttribute("disabled","");isEditingDeclaration=!1}var categories=document.getElementById("toolbox").children;
for(i=0;i<categories.length;i++)for(var category=categories[i],blocks=categories[i].children,j=0;j<blocks.length;j++){var blockName=blocks[j].getAttribute("type");if(blockName){var colour=blocks[j].hasAttribute("colour")?blocks[j].getAttribute("colour"):category.getAttribute("categorystyle");colour in Blockly.Themes.Classic.categoryStyles&&(colour=Blockly.Themes.Classic.categoryStyles[colour].colour);overrideColour(blockName,colour)}}
workspace=Blockly.inject("blockly",{comments:!0,collapse:!0,disable:!0,grid:{spacing:25,length:3,colour:"#ccc",snap:!0},horizontalLayout:!1,maxBlocks:Infinity,maxInstances:{env_on_clip_change:1},media:base+"/vendor/pxt-blockly/media/",newFunctions:!1,oneBasedIndex:!0,readOnly:!1,rtl:!1,move:{scrollbars:!0,drag:!0,wheel:!1},toolbox:document.getElementById("toolbox"),toolboxPosition:"start",toolboxOptions:{color:!0,inverted:!1},zoom:{controls:!0,wheel:!0,startScale:.8,maxScale:4,minScale:.25,scaleSpeed:1.1},
renderer:"pxt"});workspace.addChangeListener(myUpdateFunction);myUpdateFunction();declarationWorkspace=Blockly.inject("function-editor",{newFunctions:!0,scrollbars:!0,renderer:"pxt"});declarationWorkspace.showContextMenu_=function(){};Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE="function";declarationWorkspace.addChangeListener(function(){mutationRoot&&mutationRoot.updateFunctionSignature()});
Blockly.Functions.editFunctionExternalHandler=function(a,b){console.log("Showing function declaration page");$("#page-1").removeClass("d-flex").addClass("d-none");$("#page-2").removeClass("d-none").addClass("d-flex");forceResize();enableDeclarationControls();callback=b;declarationWorkspace.clear();mutationRoot=declarationWorkspace.newBlock("function_declaration");mutationRoot.domToMutation(a);mutationRoot.initSvg();mutationRoot.render(!1);declarationWorkspace.centerOnBlock(mutationRoot.id)};disableDeclarationControls();
workspace.addChangeListener(Blockly.Events.disableOrphans);
(function(){var a=function(a){$("#saveModal textarea").select();document.execCommand("copy");$("#saveModal textarea").prop("selectionEnd",0);$("#saveModalAlert").show().fadeOut(2E3)};$("#saveModal textarea").on("click",a);$("#saveModalCopy").on("click",a);$("#saveModal").on("show.bs.modal",function(a){var b=Blockly.Xml.domToText(Blockly.Xml.workspaceToDom(workspace));$(a.target).find(".modal-body textarea").val(btoa(b))});$("#saveModal").on("shown.bs.modal",function(a){$("#saveModalCopy").focus()})})();
(function(){$("#loadModal").on("show.bs.modal",function(a){$(a.target).find(".modal-body textarea").val("")});$("#loadModal").on("shown.bs.modal",function(a){$(a.target).find(".modal-body textarea").focus()});var a=function(){var a=null;try{var c=atob($("#loadModal textarea").val());a=Blockly.Xml.textToDom(c);workspace.clear();Blockly.Xml.domToWorkspace(a,workspace)}catch(e){$("#loadModalAlert").show().fadeOut(2E3);return}$("#loadModal").modal("hide")};$("#loadModalLoad").on("click",a);$("#loadModal textarea").keypress(function(b){13==
(b.keyCode?b.keyCode:b.which)&&(b.preventDefault(),a())})})();clearWorkspaceAndLoadFromXml(document.querySelector("#blockly-default"),workspace);
